apiVersion: v1
kind: Pod
metadata:
    name: sample-workload-identity-key-vault
    namespace: default
    labels:
        azure.workload.identity/use: "true"
spec:
    serviceAccountName: da-workload-sa
    containers:
      - image: ghcr.io/azure/azure-workload-identity/msal-go
        name: oidc
        env:
          - name: KEYVAULT_URL
            value: https://da-vault01.vault.azure.net/
          - name: SECRET_NAME
            value: greeting